"""resource lifecycle and versioned metering"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metering_policy_versions",
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("calculation_version", sa.String(length=40), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "policy",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("watermark", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.PrimaryKeyConstraint("cloud_id", "calculation_version"),
    )
    op.create_table(
        "metering_runs",
        sa.Column("metering_run_id", sa.Uuid(), nullable=False),
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("calculation_version", sa.String(length=40), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("watermark_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("watermark_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state_periods_processed", sa.Integer(), nullable=False),
        sa.Column("usage_records_created", sa.Integer(), nullable=False),
        sa.Column("usage_records_reused", sa.Integer(), nullable=False),
        sa.Column(
            "errors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.PrimaryKeyConstraint("metering_run_id"),
    )
    op.create_index("ix_metering_runs_cloud_time", "metering_runs", ["cloud_id", "started_at"], unique=False)
    op.create_table(
        "resource_state_periods",
        sa.Column("period_id", sa.Uuid(), nullable=False),
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=20), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("resource_name", sa.String(length=255), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("flavor_id", sa.String(length=255), nullable=True),
        sa.Column("flavor_name", sa.String(length=255), nullable=True),
        sa.Column("vcpus", sa.Integer(), nullable=True),
        sa.Column("ram_mb", sa.Integer(), nullable=True),
        sa.Column("root_disk_gb", sa.Integer(), nullable=True),
        sa.Column("ephemeral_disk_gb", sa.Integer(), nullable=True),
        sa.Column("boot_source", sa.String(length=20), nullable=True),
        sa.Column("volume_size_gb", sa.Integer(), nullable=True),
        sa.Column("volume_type", sa.String(length=255), nullable=True),
        sa.Column("openstack_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("openstack_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("history_confidence", sa.String(length=20), nullable=False),
        sa.Column("effective_time_source", sa.String(length=40), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "quality_issues",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_observation_id", sa.Uuid(), nullable=False),
        sa.Column("closing_observation_id", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closure_reason", sa.String(length=40), nullable=True),
        sa.Column("first_missing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("resource_type IN ('INSTANCE', 'VOLUME')", name="ck_period_type"),
        sa.CheckConstraint("valid_to IS NULL OR valid_to > valid_from", name="ck_period_positive"),
        sa.ForeignKeyConstraint(
            ["closing_observation_id"],
            ["resource_observations.observation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_observation_id"],
            ["resource_observations.observation_id"],
        ),
        sa.PrimaryKeyConstraint("period_id"),
    )
    op.create_index("ix_period_closed", "resource_state_periods", ["cloud_id", "closed_at"], unique=False)
    op.create_index(
        "ix_period_project_time",
        "resource_state_periods",
        ["cloud_id", "project_id", "valid_from", "valid_to"],
        unique=False,
    )
    op.create_index(
        "ix_period_resource_time",
        "resource_state_periods",
        ["cloud_id", "resource_type", "resource_id", "valid_from"],
        unique=False,
    )
    op.create_index(
        "uq_period_open",
        "resource_state_periods",
        ["cloud_id", "resource_type", "resource_id"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
        sqlite_where=sa.text("valid_to IS NULL"),
    )
    op.create_table(
        "resource_lifecycle_heads",
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=20), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("latest_period_id", sa.Uuid(), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_payload_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.ForeignKeyConstraint(
            ["latest_period_id"],
            ["resource_state_periods.period_id"],
        ),
        sa.PrimaryKeyConstraint("cloud_id", "resource_type", "resource_id"),
    )
    op.create_table(
        "usage_records",
        sa.Column("usage_record_id", sa.Uuid(), nullable=False),
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=20), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("meter_name", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("allocated_quantity", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("usage_quantity", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("source_state_period_id", sa.Uuid(), nullable=False),
        sa.Column("calculation_version", sa.String(length=40), nullable=False),
        sa.Column("metering_run_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status = 'FINAL'", name="ck_usage_final"),
        sa.CheckConstraint("allocated_quantity >= 0 AND usage_quantity >= 0", name="ck_usage_nonnegative"),
        sa.CheckConstraint(
            "period_end > period_start AND duration_seconds > 0", name="ck_usage_positive_duration"
        ),
        sa.ForeignKeyConstraint(
            ["cloud_id", "calculation_version"],
            ["metering_policy_versions.cloud_id", "metering_policy_versions.calculation_version"],
        ),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.ForeignKeyConstraint(
            ["metering_run_id"],
            ["metering_runs.metering_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_state_period_id"],
            ["resource_state_periods.period_id"],
        ),
        sa.PrimaryKeyConstraint("usage_record_id"),
        sa.UniqueConstraint(
            "source_state_period_id",
            "meter_name",
            "period_start",
            "period_end",
            "calculation_version",
            name="uq_usage_identity",
        ),
    )
    op.create_index(
        "ix_usage_project_time",
        "usage_records",
        ["cloud_id", "project_id", "period_start", "period_end"],
        unique=False,
    )
    op.create_index(
        "ix_usage_resource_meter",
        "usage_records",
        ["cloud_id", "resource_id", "meter_name", "period_start"],
        unique=False,
    )
    op.add_column("instances", sa.Column("deleted_confirmed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("resource_observations", sa.Column("project_id", sa.Uuid(), nullable=True))
    op.add_column("resource_observations", sa.Column("payload_hash", sa.String(length=64), nullable=True))
    op.add_column("volumes", sa.Column("deleted_confirmed_at", sa.DateTime(timezone=True), nullable=True))
    if op.get_bind().dialect.name == "postgresql":
        postgres_guards()


def downgrade():
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS billing_period_guard() CASCADE")
        op.execute("DROP FUNCTION IF EXISTS billing_usage_guard() CASCADE")
        op.execute("DROP FUNCTION IF EXISTS billing_policy_guard() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("volumes", "deleted_confirmed_at")
    op.drop_column("resource_observations", "payload_hash")
    op.drop_column("resource_observations", "project_id")
    op.drop_column("instances", "deleted_confirmed_at")
    op.drop_index("ix_usage_resource_meter", table_name="usage_records")
    op.drop_index("ix_usage_project_time", table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_table("resource_lifecycle_heads")
    op.drop_index(
        "uq_period_open",
        table_name="resource_state_periods",
        postgresql_where=sa.text("valid_to IS NULL"),
        sqlite_where=sa.text("valid_to IS NULL"),
    )
    op.drop_index("ix_period_resource_time", table_name="resource_state_periods")
    op.drop_index("ix_period_project_time", table_name="resource_state_periods")
    op.drop_index("ix_period_closed", table_name="resource_state_periods")
    op.drop_table("resource_state_periods")
    op.drop_index("ix_metering_runs_cloud_time", table_name="metering_runs")
    op.drop_table("metering_runs")
    op.drop_table("metering_policy_versions")
    # ### end Alembic commands ###


def postgres_guards():
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public")
    op.execute("""
        ALTER TABLE resource_state_periods ADD CONSTRAINT exclude_period_overlap
        EXCLUDE USING gist (
            cloud_id public.gist_uuid_ops WITH =,
            resource_type public.gist_text_ops WITH =,
            resource_id public.gist_uuid_ops WITH =,
            tstzrange(valid_from, valid_to, '[)') WITH &&
        )
    """)
    op.execute("""
        CREATE FUNCTION billing_period_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'Lifecycle deletion requires an explicit correction migration';
          END IF;
          IF OLD.valid_to IS NOT NULL THEN
            RAISE EXCEPTION 'Closed lifecycle periods are immutable';
          END IF;
          IF NEW.valid_to IS NULL OR NEW.closed_at IS NULL OR
            (to_jsonb(NEW) - ARRAY['valid_to','closed_at','closure_reason','closing_observation_id',
                                  'first_missing_at','deletion_confirmed_at']) IS DISTINCT FROM
            (to_jsonb(OLD) - ARRAY['valid_to','closed_at','closure_reason','closing_observation_id',
                                  'first_missing_at','deletion_confirmed_at']) THEN
            RAISE EXCEPTION 'Only closing an open lifecycle period is allowed';
          END IF;
          RETURN NEW;
        END $$
    """)
    op.execute("""CREATE TRIGGER period_immutable BEFORE UPDATE OR DELETE ON resource_state_periods
                  FOR EACH ROW EXECUTE FUNCTION billing_period_guard()""")
    op.execute("""
        CREATE FUNCTION billing_usage_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE source resource_state_periods%ROWTYPE;
        BEGIN
          IF TG_OP <> 'INSERT' THEN RAISE EXCEPTION 'Usage records are immutable'; END IF;
          SELECT * INTO source FROM resource_state_periods WHERE period_id = NEW.source_state_period_id;
          IF source.valid_to IS NULL OR NEW.period_start < source.valid_from
             OR NEW.period_end > source.valid_to
             OR NEW.cloud_id <> source.cloud_id OR NEW.project_id <> source.project_id
             OR NEW.resource_type <> source.resource_type OR NEW.resource_id <> source.resource_id THEN
            RAISE EXCEPTION 'Usage must reference matching closed lifecycle bounds';
          END IF;
          RETURN NEW;
        END $$
    """)
    op.execute("""CREATE TRIGGER usage_immutable BEFORE INSERT OR UPDATE OR DELETE ON usage_records
                  FOR EACH ROW EXECUTE FUNCTION billing_usage_guard()""")
    op.execute("""
        CREATE FUNCTION billing_policy_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Registered policies are immutable'; END IF;
          IF (to_jsonb(NEW) - 'watermark') IS DISTINCT FROM (to_jsonb(OLD) - 'watermark') THEN
            RAISE EXCEPTION 'Policy changes require a new calculation version';
          END IF;
          RETURN NEW;
        END $$
    """)
    op.execute("""CREATE TRIGGER policy_immutable BEFORE UPDATE OR DELETE ON metering_policy_versions
                  FOR EACH ROW EXECUTE FUNCTION billing_policy_guard()""")
