"""pricing catalog and immutable rating"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    op.create_index(
        "ix_usage_rating_scan", "usage_records", ["cloud_id", "calculation_version", "usage_record_id"]
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_products",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("meter_name", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("service_category", sa.String(length=40), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("meter_name"),
    )
    op.create_table(
        "price_books",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("currency IN ('VND','USD')", name="ck_book_currency"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "price_book_versions",
        sa.Column("price_book_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('DRAFT','ACTIVE','RETIRED')", name="ck_price_version_status"),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from", name="ck_price_version_bounds"
        ),
        sa.ForeignKeyConstraint(
            ["price_book_id"],
            ["price_books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("price_book_id", "version", name="uq_book_version"),
    )
    op.create_index(
        "ix_price_version_effective",
        "price_book_versions",
        ["price_book_id", "status", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_table(
        "pricing_audit_log",
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "before",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "after",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pricing_audit_time", "pricing_audit_log", ["cloud_id", "created_at"], unique=False)
    op.create_table(
        "rating_runs",
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("usage_records_processed", sa.Integer(), nullable=False),
        sa.Column("charge_records_created", sa.Integer(), nullable=False),
        sa.Column("charge_records_skipped", sa.Integer(), nullable=False),
        sa.Column("unrated_records", sa.Integer(), nullable=False),
        sa.Column(
            "errors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("rating_version", sa.String(length=40), nullable=False),
        sa.Column("usage_calculation_version", sa.String(length=40), nullable=False),
        sa.Column("force", sa.Boolean(), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rating_runs_cloud_time", "rating_runs", ["cloud_id", "started_at"], unique=False)
    op.create_table(
        "price_rules",
        sa.Column("price_book_version_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("billing_unit", sa.String(length=30), nullable=False),
        sa.Column("minimum_quantity", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("rounding_mode", sa.String(length=30), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rounding_mode = 'HALF_EVEN'", name="ck_rule_rounding"),
        sa.CheckConstraint("unit_price >= 0 AND minimum_quantity = 0", name="ck_rule_simple_price"),
        sa.ForeignKeyConstraint(
            ["price_book_version_id"],
            ["price_book_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["billing_products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("price_book_version_id", "product_id", name="uq_rule_product"),
    )
    op.create_table(
        "project_price_book_assignments",
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("price_book_id", sa.Uuid(), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from", name="ck_assignment_bounds"
        ),
        sa.ForeignKeyConstraint(
            ["cloud_id", "project_id"],
            ["projects.cloud_id", "projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.ForeignKeyConstraint(
            ["price_book_id"],
            ["price_books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_assignment_effective",
        "project_price_book_assignments",
        ["cloud_id", "project_id", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_table(
        "project_price_overrides",
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("currency IN ('VND','USD')", name="ck_override_currency"),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from", name="ck_override_bounds"
        ),
        sa.CheckConstraint("unit_price >= 0", name="ck_override_price"),
        sa.ForeignKeyConstraint(
            ["cloud_id", "project_id"],
            ["projects.cloud_id", "projects.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["billing_products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_override_effective",
        "project_price_overrides",
        ["cloud_id", "project_id", "product_id", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_table(
        "charge_records",
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=20), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("usage_record_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("product_code", sa.String(length=64), nullable=True),
        sa.Column("service_category", sa.String(length=40), nullable=True),
        sa.Column("meter_name", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("rated_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rated_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("allocated_quantity", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("usage_quantity", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("rated_quantity", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=38, scale=8), nullable=True),
        sa.Column("pricing_source", sa.String(length=30), nullable=True),
        sa.Column("price_book_id", sa.Uuid(), nullable=True),
        sa.Column("price_book_version_id", sa.Uuid(), nullable=True),
        sa.Column("price_book_version", sa.String(length=64), nullable=True),
        sa.Column("price_rule_id", sa.Uuid(), nullable=True),
        sa.Column("project_price_override_id", sa.Uuid(), nullable=True),
        sa.Column("assignment_id", sa.Uuid(), nullable=True),
        sa.Column("pricing_effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pricing_effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("formula", sa.String(length=100), nullable=False),
        sa.Column("rating_version", sa.String(length=40), nullable=False),
        sa.Column("source_usage_status", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("unrated_reason", sa.String(length=64), nullable=True),
        sa.Column("rating_run_id", sa.Uuid(), nullable=False),
        sa.Column("superseded_by_rating_run_id", sa.Uuid(), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status != 'RATED' OR (subtotal IS NOT NULL AND subtotal >= 0 "
            "AND unit_price IS NOT NULL AND unit_price >= 0 AND currency IN ('VND','USD'))",
            name="ck_charge_rated",
        ),
        sa.CheckConstraint(
            "status IN ('RATED','UNRATED','SUPERSEDED') AND source_usage_status = 'FINAL'",
            name="ck_charge_status",
        ),
        sa.CheckConstraint(
            "rated_period_end > rated_period_start AND duration_seconds > 0", name="ck_charge_bounds"
        ),
        sa.CheckConstraint("rated_quantity >= 0 AND allocated_quantity >= 0", name="ck_charge_quantity"),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["project_price_book_assignments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.ForeignKeyConstraint(
            ["price_book_id"],
            ["price_books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["price_book_version_id"],
            ["price_book_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["price_rule_id"],
            ["price_rules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["billing_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_price_override_id"],
            ["project_price_overrides.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rating_run_id"],
            ["rating_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_rating_run_id"],
            ["rating_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usage_record_id"],
            ["usage_records.usage_record_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_charge_product", "charge_records", ["product_id"], unique=False)
    op.create_index(
        "ix_charge_project_time",
        "charge_records",
        ["cloud_id", "project_id", "rated_period_start", "rated_period_end"],
        unique=False,
    )
    op.create_index(
        "ix_charge_resource_meter",
        "charge_records",
        ["cloud_id", "resource_id", "meter_name", "rated_period_start"],
        unique=False,
    )
    op.create_index("ix_charge_run", "charge_records", ["rating_run_id"], unique=False)
    op.create_index(
        "ix_charge_status_currency", "charge_records", ["cloud_id", "status", "currency"], unique=False
    )
    op.create_index(
        "uq_charge_active_segment",
        "charge_records",
        ["usage_record_id", "rated_period_start", "rated_period_end"],
        unique=True,
        postgresql_where=sa.text("status != 'SUPERSEDED'"),
        sqlite_where=sa.text("status != 'SUPERSEDED'"),
    )
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        postgres_guards()


def downgrade():
    op.drop_index("ix_usage_rating_scan", table_name="usage_records")
    if op.get_bind().dialect.name == "postgresql":
        for name in (
            "rating_charge_guard",
            "pricing_rule_guard",
            "pricing_version_guard",
            "pricing_fixed_guard",
            "pricing_retire_guard",
        ):
            op.execute(f"DROP FUNCTION IF EXISTS {name}() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_charge_active_segment",
        table_name="charge_records",
        postgresql_where=sa.text("status != 'SUPERSEDED'"),
        sqlite_where=sa.text("status != 'SUPERSEDED'"),
    )
    op.drop_index("ix_charge_status_currency", table_name="charge_records")
    op.drop_index("ix_charge_run", table_name="charge_records")
    op.drop_index("ix_charge_resource_meter", table_name="charge_records")
    op.drop_index("ix_charge_project_time", table_name="charge_records")
    op.drop_index("ix_charge_product", table_name="charge_records")
    op.drop_table("charge_records")
    op.drop_index("ix_override_effective", table_name="project_price_overrides")
    op.drop_table("project_price_overrides")
    op.drop_index("ix_assignment_effective", table_name="project_price_book_assignments")
    op.drop_table("project_price_book_assignments")
    op.drop_table("price_rules")
    op.drop_index("ix_rating_runs_cloud_time", table_name="rating_runs")
    op.drop_table("rating_runs")
    op.drop_index("ix_pricing_audit_time", table_name="pricing_audit_log")
    op.drop_table("pricing_audit_log")
    op.drop_index("ix_price_version_effective", table_name="price_book_versions")
    op.drop_table("price_book_versions")
    op.drop_table("price_books")
    op.drop_table("billing_products")
    # ### end Alembic commands ###


def postgres_guards():
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public")
    op.execute("""ALTER TABLE price_book_versions ADD CONSTRAINT exclude_active_price_versions
        EXCLUDE USING gist (price_book_id public.gist_uuid_ops WITH =,
        tstzrange(effective_from,effective_to,'[)') WITH &&) WHERE (status = 'ACTIVE')""")
    op.execute("""ALTER TABLE project_price_book_assignments ADD CONSTRAINT exclude_assignments
        EXCLUDE USING gist (cloud_id public.gist_uuid_ops WITH =,
        (COALESCE(project_id,'00000000-0000-0000-0000-000000000000'::uuid)) public.gist_uuid_ops WITH =,
        tstzrange(effective_from,effective_to,'[)') WITH &&) WHERE (retired_at IS NULL)""")
    op.execute("""ALTER TABLE project_price_overrides ADD CONSTRAINT exclude_overrides
        EXCLUDE USING gist (cloud_id public.gist_uuid_ops WITH =, project_id public.gist_uuid_ops WITH =,
        product_id public.gist_uuid_ops WITH =, tstzrange(effective_from,effective_to,'[)') WITH &&)
        WHERE (retired_at IS NULL)""")
    op.execute("""ALTER TABLE charge_records ADD CONSTRAINT exclude_active_charges
        EXCLUDE USING gist (usage_record_id public.gist_uuid_ops WITH =,
        tstzrange(rated_period_start,rated_period_end,'[)') WITH &&) WHERE (status != 'SUPERSEDED')""")
    op.execute("""CREATE FUNCTION pricing_fixed_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'Immutable pricing identity or audit record'; END $$""")
    for table in ("billing_products", "price_books", "pricing_audit_log"):
        op.execute(
            f"""CREATE TRIGGER fixed_guard BEFORE UPDATE OR DELETE ON {table}
                  FOR EACH ROW EXECUTE FUNCTION pricing_fixed_guard()"""
        )
    op.execute("""CREATE FUNCTION pricing_version_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' OR (TG_OP = 'INSERT' AND NEW.status != 'DRAFT') THEN
            RAISE EXCEPTION 'Versions must start as drafts and remain auditable'; END IF;
          IF TG_OP = 'UPDATE' THEN
            IF (to_jsonb(NEW) - ARRAY['status','activated_at']) IS DISTINCT FROM
               (to_jsonb(OLD) - ARRAY['status','activated_at']) OR
               NOT ((OLD.status='DRAFT' AND NEW.status='ACTIVE' AND NEW.activated_at IS NOT NULL)
                 OR (OLD.status='ACTIVE' AND NEW.status='RETIRED' AND NEW.activated_at=OLD.activated_at)) THEN
              RAISE EXCEPTION 'Only draft activation and active retirement allowed'; END IF;
          END IF;
          RETURN NEW;
        END $$""")
    op.execute(
        """CREATE TRIGGER version_guard BEFORE INSERT OR UPDATE OR DELETE ON price_book_versions
                  FOR EACH ROW EXECUTE FUNCTION pricing_version_guard()"""
    )
    op.execute("""CREATE FUNCTION pricing_rule_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE state text;
        BEGIN
          IF TG_OP != 'INSERT' THEN RAISE EXCEPTION 'Rules are append-only; replace draft version'; END IF;
          SELECT status INTO state FROM price_book_versions WHERE id=NEW.price_book_version_id FOR UPDATE;
          IF state IS DISTINCT FROM 'DRAFT' THEN RAISE EXCEPTION 'Only draft versions accept rules'; END IF;
          RETURN NEW;
        END $$""")
    op.execute(
        """CREATE TRIGGER rule_guard BEFORE INSERT OR UPDATE OR DELETE ON price_rules
                  FOR EACH ROW EXECUTE FUNCTION pricing_rule_guard()"""
    )
    op.execute("""CREATE FUNCTION pricing_retire_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Pricing history cannot be deleted'; END IF;
          IF OLD.retired_at IS NOT NULL OR NEW.retired_at IS NULL OR
             (to_jsonb(NEW) - ARRAY['retired_at','updated_at']) IS DISTINCT FROM
             (to_jsonb(OLD) - ARRAY['retired_at','updated_at']) THEN
             RAISE EXCEPTION 'Retire and replace pricing assignment or override'; END IF;
          RETURN NEW;
        END $$""")
    for table in ("project_price_book_assignments", "project_price_overrides"):
        op.execute(
            f"""CREATE TRIGGER retire_guard BEFORE UPDATE OR DELETE ON {table}
                  FOR EACH ROW EXECUTE FUNCTION pricing_retire_guard()"""
        )
    op.execute("""CREATE FUNCTION rating_charge_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE source usage_records%ROWTYPE;
        BEGIN
          IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Charge history cannot be deleted'; END IF;
          IF TG_OP='UPDATE' THEN
            IF OLD.status='SUPERSEDED' OR NEW.status!='SUPERSEDED' OR NEW.superseded_at IS NULL
               OR NEW.superseded_by_rating_run_id IS NULL OR
               (to_jsonb(NEW) - ARRAY['status','superseded_at','superseded_by_rating_run_id'])
               IS DISTINCT FROM
               (to_jsonb(OLD) - ARRAY['status','superseded_at','superseded_by_rating_run_id']) THEN
              RAISE EXCEPTION 'Only explicit supersession can change a charge'; END IF;
          ELSE
            SELECT * INTO source FROM usage_records WHERE usage_record_id=NEW.usage_record_id;
            IF source.status IS DISTINCT FROM 'FINAL' OR NEW.rated_period_start < source.period_start
               OR NEW.rated_period_end > source.period_end OR NEW.cloud_id != source.cloud_id
               OR NEW.project_id != source.project_id OR NEW.resource_id != source.resource_id
               OR NEW.resource_type != source.resource_type OR NEW.meter_name != source.meter_name
               OR NEW.unit != source.unit OR NEW.allocated_quantity != source.allocated_quantity THEN
              RAISE EXCEPTION 'Charge must match its final usage source'; END IF;
          END IF;
          RETURN NEW;
        END $$""")
    op.execute(
        """CREATE TRIGGER charge_guard BEFORE INSERT OR UPDATE OR DELETE ON charge_records
                  FOR EACH ROW EXECUTE FUNCTION rating_charge_guard()"""
    )
