"""Additive billing ledger. PostgreSQL guards are frozen migration SQL."""
# ruff: noqa: E501

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_number_counters",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "billing_audit_log",
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "before_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "after_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_billing_audit_log_entity_id"), "billing_audit_log", ["entity_id"], unique=False)
    op.create_table(
        "billing_cycles",
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("billing_timezone", sa.String(length=64), nullable=False),
        sa.Column("usage_calculation_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('OPEN','CALCULATING','DRAFT','REVIEW','FINALIZED','CLOSED')"),
        sa.CheckConstraint("period_start < period_end"),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cloud_id", "code"),
    )
    op.create_index(
        "ix_billing_cycle_period", "billing_cycles", ["cloud_id", "period_start", "period_end"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("invoice_number", sa.String(length=64), nullable=True),
        sa.Column("cloud_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("project_name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("billing_cycle_id", sa.Uuid(), nullable=False),
        sa.Column("billing_timezone", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=38, scale=8), nullable=False),
        sa.Column("adjustment_total", sa.Numeric(precision=38, scale=8), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=38, scale=8), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=38, scale=8), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=False),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("currency IN ('VND','USD')"),
        sa.CheckConstraint("status IN ('DRAFT','REVIEW','FINALIZED','VOID')"),
        sa.CheckConstraint("period_start < period_end"),
        sa.CheckConstraint(
            "subtotal >= 0 AND tax_total = 0 AND adjustment_total = 0 AND grand_total = subtotal"
        ),
        sa.ForeignKeyConstraint(
            ["billing_cycle_id"],
            ["billing_cycles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cloud_id"],
            ["clouds.cloud_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cloud_id", "project_id", "billing_cycle_id", "currency"),
        sa.UniqueConstraint("invoice_number"),
    )
    op.create_index("ix_invoice_cycle_status", "invoices", ["billing_cycle_id", "status"], unique=False)
    op.create_index("ix_invoice_project", "invoices", ["cloud_id", "project_id"], unique=False)
    op.create_table(
        "billing_adjustments",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("reason_text", sa.String(length=2000), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("approved_by", sa.String(length=100), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("(type='CREDIT' AND amount < 0) OR (type='DEBIT' AND amount > 0)"),
        sa.CheckConstraint("status IN ('DRAFT','APPROVED','APPLIED')"),
        sa.CheckConstraint("length(reason_code)>0 AND length(reason_text)>0"),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_billing_adjustments_invoice_id"), "billing_adjustments", ["invoice_id"], unique=False
    )
    op.create_table(
        "invoice_lines",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("line_type", sa.String(length=20), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("product_code", sa.String(length=64), nullable=False),
        sa.Column("product_name", sa.String(length=255), nullable=False),
        sa.Column("meter_name", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("usage_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("line_type = 'USAGE' AND amount >= 0 AND usage_quantity >= 0 AND unit_price >= 0"),
        sa.CheckConstraint("period_start < period_end"),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["billing_products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_lines_invoice_id"), "invoice_lines", ["invoice_id"], unique=False)
    op.create_table(
        "invoice_charge_links",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_line_id", sa.Uuid(), nullable=False),
        sa.Column("charge_record_id", sa.Uuid(), nullable=False),
        sa.Column("included_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("included_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("included_amount", sa.Numeric(precision=38, scale=8), nullable=False),
        sa.Column("included_quantity", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("included_amount >= 0 AND included_quantity >= 0"),
        sa.CheckConstraint("included_start < included_end"),
        sa.ForeignKeyConstraint(
            ["charge_record_id"],
            ["charge_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_line_id"],
            ["invoice_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_id", "charge_record_id"),
    )
    op.create_index(
        op.f("ix_invoice_charge_links_charge_record_id"),
        "invoice_charge_links",
        ["charge_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_charge_links_invoice_id"), "invoice_charge_links", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_charge_links_invoice_line_id"),
        "invoice_charge_links",
        ["invoice_line_id"],
        unique=False,
    )
    op.execute("INSERT INTO invoice_number_counters (name, value) VALUES ('invoice', 0)")
    if op.get_bind().dialect.name == "postgresql":
        guards()


def downgrade():
    if op.get_bind().dialect.name == "postgresql":
        for name in (
            "billing_frozen",
            "billing_child_guard",
            "billing_charge_guard",
            "billing_adjustment_guard",
            "billing_cycle_guard",
            "billing_counter_guard",
            "billing_lock_commit_guard",
        ):
            op.execute(f"DROP FUNCTION IF EXISTS {name}() CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_charge_links_invoice_line_id"), table_name="invoice_charge_links")
    op.drop_index(op.f("ix_invoice_charge_links_invoice_id"), table_name="invoice_charge_links")
    op.drop_index(op.f("ix_invoice_charge_links_charge_record_id"), table_name="invoice_charge_links")
    op.drop_table("invoice_charge_links")
    op.drop_index(op.f("ix_invoice_lines_invoice_id"), table_name="invoice_lines")
    op.drop_table("invoice_lines")
    op.drop_index(op.f("ix_billing_adjustments_invoice_id"), table_name="billing_adjustments")
    op.drop_table("billing_adjustments")
    op.drop_index("ix_invoice_project", table_name="invoices")
    op.drop_index("ix_invoice_cycle_status", table_name="invoices")
    op.drop_table("invoices")
    op.drop_index("ix_billing_cycle_period", table_name="billing_cycles")
    op.drop_table("billing_cycles")
    op.drop_index(op.f("ix_billing_audit_log_entity_id"), table_name="billing_audit_log")
    op.drop_table("billing_audit_log")
    op.drop_table("invoice_number_counters")
    # ### end Alembic commands ###


def guards():
    op.execute("""
        ALTER TABLE invoice_charge_links ADD CONSTRAINT ex_billed_charge_period
        EXCLUDE USING gist (charge_record_id WITH =, tstzrange(included_start,included_end,'[)') WITH &&)
        WHERE (locked_at IS NOT NULL)
    """)
    op.execute("""
    CREATE FUNCTION billing_frozen() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP='INSERT' THEN
        IF NEW.status <> 'DRAFT' OR NEW.invoice_number IS NOT NULL THEN
          RAISE EXCEPTION 'INVOICE_MUST_START_DRAFT'; END IF;
        RETURN NEW;
      END IF;
      IF TG_TABLE_NAME='billing_audit_log' OR TG_OP='DELETE' OR OLD.status='FINALIZED' THEN
        RAISE EXCEPTION 'IMMUTABLE_FINANCIAL_RECORD';
      END IF;
      IF TG_OP='UPDATE' AND OLD.status <> NEW.status AND NOT (
        (OLD.status='DRAFT' AND NEW.status IN ('REVIEW','VOID')) OR
        (OLD.status='REVIEW' AND NEW.status IN ('DRAFT','FINALIZED'))
      ) THEN RAISE EXCEPTION 'INVALID_STATE_TRANSITION'; END IF;
      IF NEW.status='FINALIZED' AND (NEW.invoice_number IS NULL OR NEW.finalized_at IS NULL
        OR NOT EXISTS(SELECT 1 FROM invoice_lines WHERE invoice_id=NEW.id)
        OR EXISTS(SELECT 1 FROM invoice_charge_links WHERE invoice_id=NEW.id AND locked_at IS NULL)
        OR NEW.subtotal <> (SELECT coalesce(sum(amount),0) FROM invoice_lines WHERE invoice_id=NEW.id)
        OR EXISTS(SELECT 1 FROM invoice_lines l WHERE l.invoice_id=NEW.id AND (
          l.currency <> NEW.currency OR l.amount <> (SELECT coalesce(sum(included_amount),-1)
            FROM invoice_charge_links WHERE invoice_line_id=l.id)
          OR l.usage_quantity <> (SELECT coalesce(sum(included_quantity),-1)
            FROM invoice_charge_links WHERE invoice_line_id=l.id))))
        THEN RAISE EXCEPTION 'RECONCILIATION_FAILED'; END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER immutable_invoice BEFORE INSERT OR UPDATE OR DELETE ON invoices FOR EACH ROW EXECUTE FUNCTION billing_frozen()"
    )
    op.execute(
        "CREATE TRIGGER immutable_billing_audit BEFORE UPDATE OR DELETE ON billing_audit_log FOR EACH ROW EXECUTE FUNCTION billing_frozen()"
    )
    op.execute("""
    CREATE FUNCTION billing_child_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE old_parent uuid; new_parent uuid;
    BEGIN
      IF TG_OP <> 'INSERT' THEN old_parent := OLD.invoice_id; END IF;
      IF TG_OP <> 'DELETE' THEN new_parent := NEW.invoice_id; END IF;
      IF EXISTS(SELECT 1 FROM invoices WHERE id IN (old_parent,new_parent) AND status='FINALIZED') THEN
        RAISE EXCEPTION 'IMMUTABLE_INVOICE'; END IF;
      IF TG_TABLE_NAME='invoice_charge_links' THEN
        IF TG_OP <> 'INSERT' AND OLD.locked_at IS NOT NULL THEN RAISE EXCEPTION 'IMMUTABLE_CHARGE_LINK'; END IF;
        IF TG_OP <> 'DELETE' AND NOT EXISTS(SELECT 1 FROM invoice_lines WHERE id=NEW.invoice_line_id AND invoice_id=NEW.invoice_id)
          THEN RAISE EXCEPTION 'INVALID_SOURCE_TRACE'; END IF;
      END IF;
      IF TG_OP='DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END $$
    """)
    for table in ("invoice_lines", "invoice_charge_links"):
        op.execute(
            f"CREATE TRIGGER immutable_invoice_child BEFORE INSERT OR UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION billing_child_guard()"
        )
    op.execute("""
    CREATE FUNCTION billing_charge_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF EXISTS(SELECT 1 FROM invoice_charge_links WHERE charge_record_id=OLD.id AND locked_at IS NOT NULL)
        THEN RAISE EXCEPTION 'BILLED_CHARGE_CONFLICT'; END IF;
      IF TG_OP='DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER billed_charge_protection BEFORE UPDATE OR DELETE ON charge_records FOR EACH ROW EXECUTE FUNCTION billing_charge_guard()"
    )
    op.execute("""
    CREATE FUNCTION billing_adjustment_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP='INSERT' THEN
        IF NEW.status <> 'DRAFT' OR NOT EXISTS(SELECT 1 FROM invoices WHERE id=NEW.invoice_id AND status='FINALIZED' AND currency=NEW.currency AND project_id=NEW.project_id)
          THEN RAISE EXCEPTION 'INVALID_ADJUSTMENT'; END IF;
        RETURN NEW;
      END IF;
      IF TG_OP='DELETE' OR OLD.status='APPLIED' THEN RAISE EXCEPTION 'IMMUTABLE_ADJUSTMENT'; END IF;
      IF (to_jsonb(NEW)-ARRAY['status','approved_at','approved_by','applied_at']) IS DISTINCT FROM
         (to_jsonb(OLD)-ARRAY['status','approved_at','approved_by','applied_at']) OR NOT (
        (OLD.status='DRAFT' AND NEW.status='APPROVED' AND NEW.approved_at IS NOT NULL AND NEW.approved_by IS NOT NULL AND NEW.applied_at IS NULL) OR
        (OLD.status='APPROVED' AND NEW.status='APPLIED' AND NEW.applied_at IS NOT NULL AND NEW.approved_at=OLD.approved_at AND NEW.approved_by=OLD.approved_by)
      ) THEN RAISE EXCEPTION 'INVALID_ADJUSTMENT_TRANSITION'; END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER adjustment_protection BEFORE INSERT OR UPDATE OR DELETE ON billing_adjustments FOR EACH ROW EXECUTE FUNCTION billing_adjustment_guard()"
    )
    op.execute("""
    CREATE FUNCTION billing_cycle_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP='DELETE' THEN RAISE EXCEPTION 'IMMUTABLE_BILLING_CYCLE'; END IF;
      IF (to_jsonb(NEW)-ARRAY['status','updated_at','finalized_at','closed_at']) IS DISTINCT FROM
         (to_jsonb(OLD)-ARRAY['status','updated_at','finalized_at','closed_at']) THEN RAISE EXCEPTION 'IMMUTABLE_CYCLE_SCOPE'; END IF;
      IF OLD.status <> NEW.status AND NOT (
        (OLD.status IN ('OPEN','DRAFT') AND NEW.status='CALCULATING') OR
        (OLD.status='CALCULATING' AND NEW.status='DRAFT') OR
        (OLD.status='DRAFT' AND NEW.status='REVIEW') OR
        (OLD.status='REVIEW' AND NEW.status IN ('DRAFT','FINALIZED')) OR
        (OLD.status='FINALIZED' AND NEW.status='CLOSED')) THEN RAISE EXCEPTION 'INVALID_STATE_TRANSITION'; END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER cycle_protection BEFORE UPDATE OR DELETE ON billing_cycles FOR EACH ROW EXECUTE FUNCTION billing_cycle_guard()"
    )
    op.execute("""
    CREATE FUNCTION billing_counter_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_OP='DELETE' OR NEW.value <= OLD.value THEN RAISE EXCEPTION 'INVOICE_NUMBER_REUSE'; END IF;
      RETURN NEW;
    END $$
    """)
    op.execute(
        "CREATE TRIGGER counter_protection BEFORE UPDATE OR DELETE ON invoice_number_counters FOR EACH ROW EXECUTE FUNCTION billing_counter_guard()"
    )

    op.execute("""
    CREATE FUNCTION billing_lock_commit_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF NEW.locked_at IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM invoices WHERE id=NEW.invoice_id AND status='FINALIZED'
      ) THEN RAISE EXCEPTION 'LOCK_REQUIRES_FINALIZED_INVOICE'; END IF;
      RETURN NULL;
    END $$
    """)
    op.execute("""CREATE CONSTRAINT TRIGGER lock_requires_finalization
      AFTER INSERT OR UPDATE ON invoice_charge_links DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW EXECUTE FUNCTION billing_lock_commit_guard()""")
